# Generated by Django 3.1.5 on 2021-01-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=60)),
                ('project_short_description', models.CharField(max_length=120)),
                ('project_description', models.TextField()),
                ('project_type', models.CharField(max_length=30)),
                ('project_image', models.ImageField(upload_to='projects/images/')),
                ('project_url', models.URLField(blank=True)),
                ('project_favorite', models.BooleanField(null=True)),
                ('project_date', models.DateField()),
            ],
        ),
    ]
